spring:
  application:
    name: sai-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/sai
    username: postgres
    password: root
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1024
        max-document-batch-size: 10000
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: never
        timeout: 5m
        max-retries: 0
      embedding:
        model: mxbai-embed-large
      chat:
        model: qwen3:4b
        options:
          model: gemma3:4b
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:9000
        toolcallback:
          enabled: true
