spring:
  application:
    name: sai-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/sai
    username: postgres
    password: root
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1024
        max-document-batch-size: 10000
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: never
        timeout: 5m
        max-retries: 0
        chat:
          additional-models:
            - qwen3:4b
            - gemma3:4b
            - llava:7b
      embedding:
        model: mxbai-embed-large
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:9000
        toolcallback:
          enabled: true

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
